# Path: agents/__init__.py

from FireStationDemander import FireStationDemander
from GreenPowerControllerAgent import GreenPowerControllerAgent
from GridControllerAgent import GridControllerAgent
from HospitalDemander import HospitalDemander
from HouseDemander import HouseDemander
from HydroEnergyGenerator import HydroEnergyGenerator
from NeighborhoodController import NeighborhoodController
from PoliceStationDemander import PoliceStationDemander
from SolarEnergyController import SolarEnergyController
from SchoolDemander import SchoolDemander
from TimeAgent import TimeAgent
from WindEnergyController import WindEnergyController

TIMEOUT = 3
